<?php
namespace Socrates\Chat\Form\Admin;

use Socrates\Chat\ExtensionUtil as E;

/**
 * Form controller class
 *
 * @see https://wiki.socrates.org/confluence/display/CRMDOC/QuickForm+Reference
 */
class Facebook extends \Socrates\Chat\Form\Good {

  function initFields(){

    $this->fields = [
      'chatbot_facebook_callback_url' => [
        'title' => 'Facebook callback URL',
        'help' => 'Facebook will send webhook updates to this callback URL. Configure your Facebook app webhook to use this URL.',
        'entity' => 'Setting',
        'field' => 'chatbot_facebook_callback_url',
        'freeze' => TRUE
      ],
      'chatbot_facebook_verify_token' => [
        'title' => 'Facebook verify token',
        'help' => 'This string is randomly generated by Socrates. You should configure your Facebook app webhook to use this token.  Update it to another value if you wish, or remove the value and save the form to generate another random token.',
        'description' => 'Facebook verify token',
        'entity' => 'Setting',
        'field' => 'chatbot_facebook_verify_token',
      ],
      'chatbot_facebook_app_secret' => [
        'title' => 'Facebook app secret',
        'help' => 'This secret is used by Facebook to authenticate messages sent from Socrates. Find it in your Facebook app, and add it here.',
        'entity' => 'Setting',
        'field' => 'chatbot_facebook_app_secret',
      ],
      'chatbot_facebook_page_access_token' => [
        'title' => 'Facebook page access token',
        'help' => 'This token is used by Facebook to authenticate messages sent from Socrates. Generate a Page access token in your Facebook app, and add it here.',
        'entity' => 'Setting',
        'field' => 'chatbot_facebook_page_access_token',
      ],
    ];

    if($this->entities['Setting']['before']['chatbot_facebook_verify_token'] == ''){
      $token = Socrates\Chat\Utils::generateToken();
      $this->entities['Setting']['before']['chatbot_facebook_verify_token'] = $token;
      socrates_api3('setting', 'create', ['chatbot_facebook_verify_token' => $token]);
    }


  }
  var $entities = [
    'Setting' => [
      'type' => 'Setting',
      'param' => 'id',
    ]
  ];

  function getDestination(){
    return Socrates\Utils_System::url('socrates/admin/chat/facebook/');
  }

  function getGoodContext() {
    return Socrates\Utils_System::url('socrates/admin/chat/facebook/');
  }

  /**
   * Generates and saves a token on page load if one does not exist already
   */
  function setDefaultToken(){
  }

}
