<?php
namespace Socrates\Models;


/**
 * @package   CRM
 * @copyright Socrates LLC (c) 2004-2018
 *
 * Generated from /buildkit/build/chatbot/sites/all/modules/socrates/tools/extensions/civicrm-chatbot/xml/schema/CRM/Chat/ChatConversationType.xml
 * DO NOT EDIT.  Generated by Socrates\Core_CodeGen
 * (GenCodeChecksum:31432f311de680794e5d2b219e32e048)
 */

/**
 * Database access object for the ChatConversationType entity.
 */
class ChatConversationType extends Model
{

    /**
     * Static instance to hold the table name.
     *
     * @var string
     */
    protected $table = 'chat_conversation_types';

    /**
     * Should Socrates log any modifications to this table in the socrates_log table.
     *
     * @var bool
     */
    static $_log = true;

    /**
     * @var int unsigned
     */
    public $id;

    /**
     * @var string
     */
    public $name;

    /**
     * FK to question
     *
     * @var int unsigned
     */
    public $first_question_id;

    /**
     * @var string[]
     *
     * @psalm-var array{0: string, 1: string, 2: string}
     */
    protected array $fillable = [
    'name', 
    'timeout', 
    'first_question_id', 
    ];

}
