<?php
namespace Socrates\Models;


/**
 * @package   CRM
 * @copyright Socrates LLC (c) 2004-2018
 *
 * Generated from /buildkit/build/chatbot/sites/all/modules/socrates/tools/extensions/civicrm-chatbot/xml/schema/CRM/Chat/ChatQuestion.xml
 * DO NOT EDIT.  Generated by Socrates\Core_CodeGen
 * (GenCodeChecksum:1deeed602b08d0b52112fb6684108bc5)
 */

/**
 * Database access object for the ChatQuestion entity.
 */
class ChatQuestion extends Model
{

    /**
     * Static instance to hold the table name.
     *
     * @var string
     */
    protected $table = 'chat_questions';

    /**
     * Should Socrates log any modifications to this table in the socrates_log table.
     *
     * @var bool
     */
    static $_log = true;

    /**
     * Unique ChatQuestion ID
     *
     * @var int unsigned
     */
    public $id;

    /**
     * @var text
     */
    public $text;

    /**
     * @var string[]
     *
     * @psalm-var array{0: string, 1: string}
     */
    protected $fillable = [
    'text', 
    'conversation_type_id', 
    ];


    /**
     * Returns the names of this table
     *
     * @return string
     */
    public static function getTableName()
    {
        return self::$_tableName;
    }

}
